spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abc8790248241@gmail.com
    password: abcdef2019!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
     
